# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  ConvLib_config = debug
  Main_config = debug

else ifeq ($(config),release)
  ConvLib_config = release
  Main_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := ConvLib Main

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

ConvLib:
ifneq (,$(ConvLib_config))
	@echo "==== Building ConvLib ($(ConvLib_config)) ===="
	@${MAKE} --no-print-directory -C ConvLib -f Makefile config=$(ConvLib_config)
endif

Main: ConvLib
ifneq (,$(Main_config))
	@echo "==== Building Main ($(Main_config)) ===="
	@${MAKE} --no-print-directory -C Main -f Makefile config=$(Main_config)
endif

clean:
	@${MAKE} --no-print-directory -C ConvLib -f Makefile clean
	@${MAKE} --no-print-directory -C Main -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   ConvLib"
	@echo "   Main"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"